### ISSUE TITLE
OverrideTextFieldColor is always black

### ISSUE THREAD

**Issue by fib-nm** [Keyitdev/sddm-astronaut-theme#10]
If you set
```OverrideTextFieldColor=""```
then selected text always has the same color as `AccentColor` and is impossible to read.

If you set `OverrideTextFieldColor` to anything, e.g.
```OverrideTextFieldColor="#123456"```
then selected text is always black.

**Comment by Keyitdev** [comment]
It was recently added and I didn't test it. (https://github.com/Keyitdev/sddm-astronaut-theme/commit/b97e5d9a9d4db31178d6a436d259dc9944999fd5). I will check it. Ty for letting me know.

**Comment by Keyitdev** [comment]
![image](https://github.com/user-attachments/assets/7bb0eea5-1fdb-4a41-abc0-0aec062e3d27)
I just set OverrideTextFieldColor="#ff00ff" and it works for me.
![image](https://github.com/user-attachments/assets/ab7e0631-076b-4120-882e-06f13517d344)
OverrideTextFieldColor="#00ff00"

Can you send me your config and screenshot?

**Comment by fib-nm** [comment]
> I just set OverrideTextFieldColor="#ff00ff" and it works for me.
> 
> Can you send me your config and screenshot?

I'm sorry, I messed up. I forgot to write # before color. Now it works. Sorry for causing this much trouble.
