### ISSUE TITLE
Theme not Launching

### ISSUE THREAD

**Issue by yellow280** [Keyitdev/sddm-astronaut-theme#11]
followed the instructions for **arch Linux**, rebooted and the SDDM theme remand the same as it was. (default)
     DE=**Hyprland**
     Distro=**Arch**
PS: I have downloaded the dependency and edited /etc/sddm.conf as listed in instructions,

**Comment by Keyitdev** [comment]
Run:
`cat /etc/sddm.conf` and give me output.
Then run:
`sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-theme/`
see what happens and also give me output.

**Comment by alessandriniluca** [comment]
Hi, sorry for bumping in, but I'm facing the same problem, on a fresh arch + hyprland setup

`cat /etc/sddm.conf` returns:
```
[theme]
Current=sddm-astronaut-theme
```

`sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-theme/` correctly starts the astronaut theme IF and only if I already started hyprland (not from tty). At login, no theme is loaded.

Further info:

- Installed the full group [qt6](https://archlinux.org/groups/x86_64/qt6/)

**Comment by Keyitdev** [comment]
@alessandriniluca I think that this problem is connected with Wayland, because this bug only happens with Hyprland (no problems with X11). I will look at it closer tomorrow. 
Btw this might help: https://www.reddit.com/r/hyprland/comments/18hom53/how_did_you_configure_sddm_to_run_hyprland/

**Comment by alessandriniluca** [comment]
**[solved for me]**
Sorry, I accidentally deleted my previous comment, while I wanted to modify it. For who will came in the future, I was saying I was facing a similar problem to the one of @yellow280 with the following behavior:

No theme at login, but `sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-theme/` correctly started it.

I accidentally typed `theme` instead of `Theme` in `/etc/sddm.conf`. This might also be the case of @yellow280.

Apologize me, but I don't know why, it took me a while (an hour more or less) to notice the typo ahah

**Comment by Keyitdev** [comment]
@alessandriniluca  No problem, everyone makes typos sometimes. I'm glad you fixed it and that it's not a Hyprland problem, but just a typo.

Cheers

Btw I can undelete your comment.
Here is what he said:

Hi, sorry for bumping in, but I'm facing the same problem, on a fresh arch + hyprland setup

`cat /etc/sddm.conf` returns:

```
[theme]
Current=sddm-astronaut-theme
```
`sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-theme/` correctly starts the astronaut theme IF and only if I already started hyprland (not from tty). At login, no theme is loaded.

Further info:
- Installed the full group qt6

**Comment by yellow280** [comment]
Thank you so much it solved everything :D

**Comment by alessandriniluca** [comment]
[celebrate]     Luca Alessandrini reacted to your message:
________________________________
