### ISSUE TITLE
Change to preview2

### ISSUE THREAD

**Issue by grummans** [Keyitdev/sddm-astronaut-theme#12]
How can I change SDDM layout like "preview2" (show background image + login form without blur effect)? I see you wrote that "You can easily change how it looks in [config](https://github.com/Keyitdev/sddm-astronaut-theme/blob/master/theme.conf)." but I clicked the link, the result is 404 not found

**Comment by Keyitdev** [comment]
I fixed the link. Ty. 
You need to edit the configuration to change its appearance.
If you want something like preview2
set PartialBlur="true" to false in https://github.com/Keyitdev/sddm-astronaut-theme/blob/07e7105aec5dd0b10631fc1f9ab2e84a6dedad51/Themes/theme1.conf#L73

**Comment by grummans** [comment]
I really like your dotfile config, but I use your rice in PC that will have no battery, no backlight, ... ^^ I just want to ask if there is a PC version of the hypr config? I think that a cool idea :v

**Comment by Keyitdev** [comment]
I'm glad to hear that. There is currently no PC-specific version, but there is a huge update coming soon (v4 version), so a lot of the problems will be solved. You can easily edit the polybar configuration if you want to remove the battery and backlight modules:
https://github.com/Keyitdev/dotfiles/blob/fa1bbd450250bb7364da9449f3834a3575dd9688/config/polybar/config.ini#L38 
just remove the modules you don't want.
Ps. My dotfiles contain the configurations for i3wm + polybar. I do not create dotfiles for hypr.

**Comment by grummans** [comment]
Thanks a lot bro <3 Hope you will have more and more beautiful rice with any Linux distro. Thank for your distribution for Linux world ^^
