### ISSUE TITLE
error not working

### ISSUE THREAD

**Issue by skarpinis** [Keyitdev/sddm-astronaut-theme#13]
same issues https://github.com/Keyitdev/sddm-astronaut-theme/issues/3#issue-2308923842
linux mint qt6 installed sudo apt install qt6-base-dev any help or only working on arch bleeding edge distros

**Comment by Keyitdev** [comment]
Should work if u have qt6.
You can test it (qt6) by running:
```
sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-theme
```
Do you have exactly the same issue? (Library import requires a version) 
Or any other?
It could also be the lack of qt6 svg package.

**Comment by skarpinis** [comment]
> Should work if u have qt6. You can test it (qt6) by running:
> 
> ```
> sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-theme
> ```
> 
> Do you have exactly the same issue? (Library import requires a version) Or any other? It could also be the lack of qt6 svg package.

Hi, yes 
sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-theme
sddm-greeter-qt6: command not found
:(

**Comment by Keyitdev** [comment]
Do you have sddm installed? And which version?
You can try to install it: `sudo apt install sddm`

**Comment by skarpinis** [comment]
0.20.0-2ubuntu4.2 I see thanks for help anyway
