### ISSUE TITLE
theme not working

### ISSUE THREAD

**Issue by xienuss** [Keyitdev/sddm-astronaut-theme#3]
when i previewing the theme SDDM shows me this error:
![2024-05-21-235528_hyprshot](https://github.com/Keyitdev/sddm-astronaut-theme/assets/160603682/56b3e3a9-47e6-45de-bc35-500ca7697c61)
when i reboot or run it through terminal its just default theme without errors

**Comment by Keyitdev** [comment]
You are probably using qt5. It is qt6 theme. Try 
`sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-theme`
instead of 
`sddm-greeter --test-mode --theme /usr/share/sddm/themes/sddm-astronaut-them `
See more here https://stackoverflow.com/questions/71991342/cant-use-qt5compat-graphicaleffects-as-it-requires-a-version.

Also on the screenshot you have strange path.

qt6 vs qt5 
![image](https://github.com/Keyitdev/sddm-astronaut-theme/assets/70140437/3603d117-e77d-4df0-9d99-20248651a9b0)

**Comment by xienuss** [comment]
it worked but i dont really know how to switch qt5 to qt6, on boot the theme is still default

**Comment by Keyitdev** [comment]
I don't know what sddm version (and distro)  you are using. But just try to install newest sddm and get rid of the old one.

> My distro (opensuse tumbleweed) left the qt5 of sddm installed and didn't install the new version 'sddm-qt6'.
> Manually removing the old qt5 sddm and installing the new one, fixed the problem. 

https://www.reddit.com/r/kde/comments/1bg2p93/kde_sddm_login_screen_is_not_changing/

**Comment by xienuss** [comment]
will try it later, thank you in advance :D

**Comment by xienuss** [comment]
> I don't know what sddm version (and distro) you are using. But just try to install newest sddm and get rid of the old one.

unfortunately arch repository doesnt have qt6 version of sddm package, tried to install git version but it gives same results as regular one. Any ideas now? (p.s. also checked SDDM's issues page and found nothing about it :[ )

**Comment by Keyitdev** [comment]
I'm pretty sure that arch have qt6 version of sddm. 
Maybe just try to reinstall theme.

```sh
sudo git clone https://github.com/keyitdev/sddm-astronaut-theme.git /usr/share/sddm/themes/sddm-astronaut-theme
sudo cp /usr/share/sddm/themes/sddm-astronaut-theme/Fonts/* /usr/share/fonts/
```
```sh
echo "[Theme]
Current=sddm-astronaut-theme" | sudo tee /etc/sddm.conf
```
https://wiki.archlinux.org/title/SDDM#Theme_settings
If previewing works, your theme should also.

If that doesn't help, I don't think I can help you. Sorry.

**Comment by xienuss** [comment]
sorry for long inactivity, it worked, tysm!
