### ISSUE TITLE
AccentColor issue

### ISSUE THREAD

**Issue by IronGreninja** [Keyitdev/sddm-astronaut-theme#4]
![Screenshot_20240602_230418](https://github.com/Keyitdev/sddm-astronaut-theme/assets/92992745/6497e778-05b2-4812-b3de-e7275946a911)

The text color of password/username when focused and typing is hard to see. Changing AccentColor to white fixes this but it also changes hover color for user/session selection. Is there a way to decouple them?

**Comment by Keyitdev** [comment]
Yes, this can be changed in QML.
For example, if you want to change the color of the user icon that is hovered over, go to `Input.qml`. 
Find `usernameField` and `usernameIcon` and in `states` change the color.
```
 icon.color: 00FF00
 ```
or
```
 icon.color: Qt.lighter(root.palette.text, 1.8)
```
https://github.com/Keyitdev/sddm-astronaut-theme/blob/ae6b7a4ad8d14da1cc3c3b712f1241b75dcfe836/Components/Input.qml#L186

This also may help

https://github.com/Keyitdev/sddm-astronaut-theme/blob/ae6b7a4ad8d14da1cc3c3b712f1241b75dcfe836/Main.qml#L22-L26

**Comment by IronGreninja** [comment]
I'm sorry, but it's not working. The issue is not the black icons. They are black only in `sddm-greeter-qt6 --test-mode` for some reason but respect IconColor when actually logging in. I just want to make the text white when typing(focussed/pressed) in the password/username input box.

I think the solution is to make it follow the MainColor and not the AccentColor. Or make a separate option like TextColor maybe.

I was making a nix derivation for the theme and it will be nice if you could implement it, so I dont have to fiddle with any qml files and just put the overrides in `theme.conf.user`.
