### ISSUE TITLE
change default AccentColor

### ISSUE THREAD

**Issue by DaniD3v** [Keyitdev/sddm-astronaut-theme#8]
I am aware this can be configured but I find the default AccentColor very hard to read. Especially if you move the form to the left

![image](https://github.com/Keyitdev/sddm-astronaut-theme/assets/124387056/25474d01-bc6f-4802-9eb2-b0d3b9c285e5)

#8a73a1 works quite well and also looks a bit nicer. I was wondering whether we could make that a default?

Here's a screenshot: 
![image](https://github.com/Keyitdev/sddm-astronaut-theme/assets/124387056/8bf8969c-79cf-4d39-a321-1169d97baeb4)

Old default with the form in the center:
![image](https://github.com/Keyitdev/sddm-astronaut-theme/assets/124387056/e10ab434-80bd-4474-bd0b-86255f5dfaa7)

With the form in the center:
![image](https://github.com/Keyitdev/sddm-astronaut-theme/assets/124387056/7ced037a-4070-4fa0-b1cb-caed2a29b968)

The one with the form in the center doesn't contrast the image as much, but that doesn't really matter because it's different from the dark input form field

(this)
![image](https://github.com/Keyitdev/sddm-astronaut-theme/assets/124387056/f3d58dac-7c4f-4619-9677-f64093f15816)

**Comment by Keyitdev** [comment]
The default config works, this color comes from the specific palette.
If you want to modify the configuration, you have to take into account that something else will also have to be changed.
